//mockData.js

export const mockSimulationResult = {
  price_trajectory: [
    { month: 1, palm_price: 142.5, mustard_price: 178.2 },
    { month: 2, palm_price: 148.3, mustard_price: 181.4 },
    { month: 3, palm_price: 151.1, mustard_price: 183.7 }
  ],
  domestic_price_change: +12.4,
  import_volume_change: -18,
  substitution_effect: +9.2,
  atma_nirbhar_before: 34.1,
  atma_nirbhar_after: 38.7,
  farmer_impact: {
    top_state: "Rajasthan",
    income_delta_per_farmer: 3200,
    farmers_benefited_lakhs: 18,
    farmer_protection_score: 74,
    state_breakdown: [
      { state: "Rajasthan", farmers_lakhs: 8.2, income_delta: 3200 },
      { state: "Madhya Pradesh", farmers_lakhs: 5.1, income_delta: 2800 },
      { state: "Haryana", farmers_lakhs: 2.4, income_delta: 3100 }
    ]
  },
  consumer_impact: {
    example_household: "₹15,000/month Household in Chennai",
    monthly_extra_cost: 287,
    pct_of_income: 4.1,
    consumer_affordability_score: 48,
    decile_breakdown: [
      { decile: "Bottom 10%", monthly_extra: 187, pct_income: 8.2 },
      { decile: "Bottom 20%", monthly_extra: 210, pct_income: 6.1 },
      { decile: "Middle 50%", monthly_extra: 287, pct_income: 4.1 },
      { decile: "Top 20%", monthly_extra: 320, pct_income: 1.2 }
    ]
  },
  state_impact: [
    { state: "Rajasthan", net: "farmer", magnitude: 0.9 },
    { state: "Tamil Nadu", net: "consumer", magnitude: 0.8 },
    { state: "West Bengal", net: "consumer", magnitude: 0.7 },
    { state: "Madhya Pradesh", net: "farmer", magnitude: 0.7 },
    { state: "Maharashtra", net: "mixed", magnitude: 0.5 },
    { state: "Uttar Pradesh", net: "farmer", magnitude: 0.6 },
    { state: "Haryana", net: "farmer", magnitude: 0.8 },
    { state: "Punjab", net: "farmer", magnitude: 0.5 },
    { state: "Gujarat", net: "mixed", magnitude: 0.4 },
    { state: "Karnataka", net: "consumer", magnitude: 0.6 },
    { state: "Kerala", net: "consumer", magnitude: 0.9 },
    { state: "Andhra Pradesh", net: "consumer", magnitude: 0.5 },
    { state: "Odisha", net: "mixed", magnitude: 0.3 },
    { state: "Bihar", net: "farmer", magnitude: 0.4 },
    { state: "Jharkhand", net: "mixed", magnitude: 0.3 }
  ],
  fiscal_impact_crore: -4200
};

export const mockPolicyReport = {
  think_tank: {
    report: `# OILNITI POLICY BRIEF
## Prepared for: Policy Research Use
**Simulation Parameters**: CPO Duty 20% | RPO Duty 32.5%
**Generated**: 18 May 2026 | **Model Version**: OilNiti 1.0
**Backtested Accuracy**: 3.6% error (Sept 2024 validation)

### Section 1 — Policy Context
This brief simulates the impact of raising CPO import duty to 20% and RPO to 32.5%. The analysis covers price transmission, farmer welfare, consumer burden, and fiscal implications across 19 states.

### Section 2 — Executive Summary
- Domestic palm oil retail price: projected +11.4% within 8 weeks
- Import volume: projected -18.3% (price elasticity applied)
- Farmers directly benefited: 18.2 lakh mustard farmers, Rajasthan leads
- Consumer burden peak: Bihar low-income households, +₹287/month, 4.8% of income
- Net fiscal gain: +₹4,200 crore estimated customs revenue annually

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by OilNiti's structural causal model
backtested to 3.6% error against September 2024 DFPD data.
Not for redistribution without attribution.
oil-niti.vercel.app`
  },
  journalist: {
    report: `# OILNITI PRESS INTELLIGENCE BRIEF
**For editorial use — not for direct publication**
CPO Duty: 20% | RPO Duty: 32.5% | Generated: 18 May 2026

# A family earning ₹12,000/month in Bihar will pay ₹287 more every month for cooking oil. That's 4.8% of their entire income. Gone.

### Ready-to-use story angles:
**ANGLE 1 — Consumer impact story:**
"India's latest palm oil duty hike will cost a low-income Bihar household ₹3,444 extra this year — more than a month's cooking gas budget."

**ANGLE 2 — Farmer welfare story:**
"18 lakh mustard farmers in Rajasthan stand to gain ₹3,200 per season from the duty change — but sunflower farmers in Andhra Pradesh remain below MSP."

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by OilNiti's structural causal model
backtested to 3.6% error against September 2024 DFPD data.
Not for redistribution without attribution.
oil-niti.vercel.app`
  },
  trader: {
    report: `# OILNITI TRADE INTELLIGENCE BRIEF
**MARKET SENSITIVE — INTERNAL USE ONLY**
Simulation: CPO 20% | RPO 32.5% | Generated: 18 May 2026

## PROCUREMENT RECOMMENDATION
- **ACTION**: BUY NOW — before implementation
- **WINDOW**: 2-3 weeks at current price
- **EXPECTED PRICE MOVE**: +11.4%
- **OPTIMAL OIL**: Soybean (stable, -3% MoM)
- **SUBSTITUTE RATIO**: 60:40 palm:soybean

### Price impact by oil type:
| Oil Type | Current Price | Post-Duty Projected | Change |
|---|---|---|---|
| CPO | ₹98/litre | ₹109/litre | +11.4% |
| Soybean Oil | ₹108/litre | ₹112/litre | +3.7% |

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by OilNiti's structural causal model
backtested to 3.6% error against September 2024 DFPD data.
Not for redistribution without attribution.
oil-niti.vercel.app`
  }
};
